export function loginPage(nonce) {
  return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>设备授权 · DSH</title><style>body{font:18px system-ui;max-width:650px;margin:12vh auto;padding:24px}#code{font: bold 36px monospace;letter-spacing:4px}button{padding:10px}pre{white-space:pre-wrap;overflow-wrap:anywhere}</style></head><body><h1>授权此浏览器</h1><p>在运行 DSH 的机器上使用本机命令批准下面的授权码。只批准你自己发起的申请。</p><p id="code">正在申请…</p><pre id="command"></pre><p id="status" role="status">授权码十分钟内有效，批准后登录有效期由服务器配置（通常为30天）。</p><button id="retry" hidden>重新申请</button><script nonce="${nonce}">
  (()=>{let secret,timer,expiresAt=0,backoff=2000;const code=document.querySelector('#code'),status=document.querySelector('#status'),retry=document.querySelector('#retry');
  async function post(path,body){const r=await fetch('/auth/device-code/'+path,{method:'POST',credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok){const e=new Error(r.status===429?'请求过于频繁，正在重试':'申请已过期或服务已重启，请重新申请');e.status=r.status;e.delay=Math.min(30000,Math.max(2000,Number(r.headers.get('Retry-After')||2)*1000));throw e}return r.json()}
  function finish(message){secret=undefined;status.textContent=message;retry.hidden=false}
  async function poll(){if(Date.now()>=expiresAt){finish('申请已过期，请重新申请');return}try{const r=await post('status',{secret});backoff=2000;if(r.state==='approved'){secret=undefined;location.replace('/');return}if(r.state==='denied'){finish('申请已被拒绝');return}status.textContent='等待本机批准…';timer=setTimeout(poll,2000)}catch(e){if(e.status&&e.status!==429&&e.status<500){finish(e.message);return}status.textContent='连接暂不可用，正在重试…';backoff=Math.min(30000,Math.max(backoff*2,e.delay||0));timer=setTimeout(poll,backoff)}}
  async function start(){clearTimeout(timer);secret=undefined;retry.hidden=true;try{const r=await post('create',{});secret=r.secret;expiresAt=r.expiresAt;backoff=2000;code.textContent=r.code;document.querySelector('#command').textContent='dsh-device-auth approve '+r.code;status.textContent='等待本机批准；此处不验证申请者身份。请在10分钟内完成。';timer=setTimeout(poll,2000)}catch(e){finish(e.message)}}
  retry.onclick=start;start();})();</script></body></html>`;
}
